
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - authentication-service
      - institute-service
      - telecalling-service
      - training-service
    networks:
      - app-network
    
  authentication-service:
    build:
      context: ./services/authentication
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - PORT_GRPC=3001
      - DB_HOST=auth-db
      - DB_PORT=3306
      - DB_NAME=auth
      - DB_USER=auth
      - DB_PASS=123456
    depends_on:
      - auth-db
    networks:
      - app-network
    
  institute-service:
    build:
      context: ./services/institute
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - PORT_GRPC=3003
      - DB_HOST=institute-db
      - DB_PORT=3306
      - DB_NAME=institute
      - DB_USER=institute
      - DB_PASS=123456
    depends_on:
      - institute-db
    networks:
      - app-network
    
  telecalling-service:
    build:
      context: ./services/telecalling
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DB_HOST=telecalling-db
      - DB_PORT=3306
      - DB_NAME=telecalling
      - DB_USER=telecalling
      - DB_PASS=123456
    depends_on:
      - telecalling-db
    networks:
      - app-network
  
  training-service:
    build:
      context: ./services/training
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DB_HOST=training-db
      - DB_PORT=3306
      - DB_NAME=training
      - DB_USER=training
      - DB_PASS=123456
    depends_on:
      - training-db
    networks:
      - app-network

  payment-service:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      - PORT=3011
      - DB_HOST=payment-db
      - DB_PORT=3306
      - DB_NAME=payment
      - DB_USER=payment
      - DB_PASS=123456
    depends_on:
      - payment-db
    networks:
      - app-network
  

  auth-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: 123456
    volumes:
      - auth_data:/var/lib/mysql
    networks:
      - app-network
  
  institute-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: institute
      MYSQL_USER: institute
      MYSQL_PASSWORD: 123456
    volumes:
      - institute_data:/var/lib/mysql
    networks:
      - app-network
  
  telecalling-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telecalling
      MYSQL_USER: telecalling
      MYSQL_PASSWORD: 123456
    volumes:
      - telecalling_data:/var/lib/mysql
    networks:
      - app-network
  
  training-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
      MYSQL_USER: training
      MYSQL_PASSWORD: 123456
    volumes:
      - training_data:/var/lib/mysql
    networks:
      - app-network
  
  payment-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: 123456
    volumes:
      - payment_data:/var/lib/mysql
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

networks:
  app-network:

volumes:
  auth_data:
  institute_data:
  telecalling_data:
  training_data:
  payment_data:    