
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - authentication-service
      - institute-service
      - telecalling-service
      - training-service
    networks:
      - app-network
    
  authentication-service:
    build:
      context: ./services/authentication
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - PORT_GRPC=3001
      - DB_HOST=auth-db
      - DB_PORT=3306
      - DB_NAME=auth
      - DB_USER=auth
      - DB_PASS=123456
    depends_on:
      - auth-db
    networks:
      - app-network
    
  institute-service:
    build:
      context: ./services/institute
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - PORT_GRPC=3003
      - DB_HOST=institute-db
      - DB_PORT=3306
      - DB_NAME=institute
      - DB_USER=institute
      - DB_PASS=123456
    depends_on:
      - institute-db
    networks:
      - app-network
    
  telecalling-service:
    build:
      context: ./services/telecalling
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DB_HOST=telecalling-db
      - DB_PORT=3306
      - DB_NAME=telecalling
      - DB_USER=telecalling
      - DB_PASS=123456
    depends_on:
      - telecalling-db
    networks:
      - app-network
  
  training-service:
    build:
      context: ./services/training
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DB_HOST=training-db
      - DB_PORT=3306
      - DB_NAME=training
      - DB_USER=training
      - DB_PASS=123456
    depends_on:
      - training-db
    networks:
      - app-network
  

  auth-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: 123456
    volumes:
      - auth_data:/var/lib/mysql
    networks:
      - app-network
  
  institute-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: institute
      MYSQL_USER: institute
      MYSQL_PASSWORD: 123456
    volumes:
      - institute_data:/var/lib/mysql
    networks:
      - app-network
  
  telecalling-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telecalling
      MYSQL_USER: telecalling
      MYSQL_PASSWORD: 123456
    volumes:
      - telecalling_data:/var/lib/mysql
    networks:
      - app-network
  
  training-db:
    image: mysql:9.6.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
      MYSQL_USER: training
      MYSQL_PASSWORD: 123456
    volumes:
      - training_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  auth_data:
  institute_data:
  telecalling_data:
  training_data: